# Generated by Django 4.1.1 on 2022-09-27 12:24

from django.db import migrations
from django.core.management import call_command


def populate_employee(apps, schema):
    call_command("loaddata", "emp_data.json")


class Migration(migrations.Migration):
    dependencies = [
        ('employee', '0007_remove_employee_age'),
    ]

    operations = [
        migrations.RunPython(populate_employee),
    ]
