# Generated by Django 4.1.1 on 2022-09-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_employee_age_alter_employee_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
