# Generated by Django 4.1.1 on 2022-09-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_employee_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
