# Generated by Django 4.1.1 on 2022-09-28 06:44

from django.db import migrations
from django.core.management import call_command


def load_employee_data(appas, schema):
    call_command("loaddata", "emp_data.json")


class Migration(migrations.Migration):
    dependencies = [
        ('employee', '0012_alter_employee_address'),
    ]

    operations = [
        migrations.RunPython(load_employee_data)
    ]
