# Generated by Django 4.1.1 on 2022-09-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_add_employee_fixture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.AlterField(
            model_name='employee',
            name='forename',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
